apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaultpolicies.vault.local
spec:
  scope: Cluster
  group: vault.local
  version: v1
  names:
    kind: Policy
    plural: vaultpolicies
    singular: vaultpolicy
